- name: Creates directory databases
  file: path=/root/databases state=directory

- name: Test if already downloaded
  stat: path=/root/databases/{{ chemblversion }}_1_mysql.tar.gz
  register: st

- name: Download Chembl
  shell: "wget -O /root/databases/{{ chemblversion }}_1_mysql.tar.gz ftp://ftp.ebi.ac.uk/pub/databases/chembl/ChEMBLdb/latest/{{ chemblversion }}_1_mysql.tar.gz"
  when: not st.stat.exists

- name: Test if already extracted
  stat: path=/root/databases/{{ chemblversion }}_1_mysql/{{ chemblversion }}_1_mysql.sql
  register: mys

- name: Extract Database
  shell: "tar -xvzf /root/databases/{{ chemblversion }}_1_mysql.tar.gz -C /root/databases/"
  when: not mys.stat.exists

- name: check if DB {{ chemblversion }} exists
  shell: mysql -uroot -p{{ mysql_root_password }} -e 'SHOW DATABASES;' | grep {{ chemblversion }}
  register: dbstatuschembl
  ignore_errors: True

- name: Create Application Database  {{ chemblversion }}
  mysql_db: login_user=root login_password={{ mysql_root_password }} name={{ chemblversion }} encoding=utf8 collation=utf8_bin state=present
  when: dbstatuschembl.rc != 0

- name: Import {{ chemblversion }}.sql similar to mysql -u <username> -p <password> < hostname.sql
  mysql_db: login_user=root login_password={{ mysql_root_password }} state=import name={{ chemblversion }} target=/root/databases/{{ chemblversion }}_1_mysql/{{ chemblversion }}_1_mysql.sql
