---
# This playbook contains common plays that will be run on all nodes.

- name: Install ntp
  yum: name=ntp state=present
  tags: ntp

- name: Install epel release
  yum: name=epel-release state=present

- name: Install wget
  yum: name=wget state=present

- name: Install nano
  yum: name=nano state=present

- name: Install bc
  yum: name=bc state=present

- name: Install byobu
  yum: name=byobu state=present

- name: Install common dependencies
  yum: name={{ item }} state=installed
  with_items:
   - libselinux-python
   - libsemanage-python
   - firewalld

- name: Pose host
  template: src=hosts.j2 dest=/etc/hosts

- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  service: name=ntpd state=started enabled=yes
  tags: ntp
